name: blue-green-deployment

services:
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_PORT=${APP_PORT:-3000}
    ports:
      - "8081:${APP_PORT:-3000}"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:${APP_PORT:-3000}/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_PORT=${APP_PORT:-3000}
    ports:
      - "8082:${APP_PORT:-3000}"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:${APP_PORT:-3000}/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
      - nginx_logs:/var/log/nginx
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - APP_PORT=${APP_PORT:-3000}
    networks:
      - app_network
    depends_on:
      app_blue:
        condition: service_healthy
      app_green:
        condition: service_healthy
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:80/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3

  alert_watcher:
    image: python:3.11-slim
    container_name: alert_watcher
    volumes:
      - nginx_logs:/var/log/nginx:ro
      - ./watcher.py:/app/watcher.py:ro
      - ./requirements.txt:/app/requirements.txt:ro
    working_dir: /app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python -u watcher.py"
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ACTIVE_POOL=${ACTIVE_POOL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD:-2}
      - WINDOW_SIZE=${WINDOW_SIZE:-200}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC:-300}
      - MAINTENANCE_MODE=${MAINTENANCE_MODE:-false}
    networks:
      - app_network
    depends_on:
      - nginx
    restart: unless-stopped

networks:
  app_network:
    name: blue_green_network
    driver: bridge

volumes:
  nginx_logs:
